### ISSUE TITLE
Version Mismatch

### ISSUE THREAD

**Issue by thebitanpaul** [Dgarc359/py-voice-clone#1]
Please mention all the specific versions of all the dependencies like torch, TTS, coqui-tts, numpy and also mention the python version you have used. Else it throws multiple version mismatch errors.

**Comment by Dgarc359** [comment]
Hi there, @thebitanpaul 

Thanks for creating this issue! Have you installed poetry and ran `poetry install`? Versions are locked with the `poetry.lock` file.

If you are still receiving errors after using poetry, please post them in this issue so I can help resolve them. Thank you!

Thanks for pointing out about the python version. Please note the poetry toml file also [declares valid python versions](https://github.com/Dgarc359/py-voice-clone/blob/b04c04aa3bfa04129059181c4d4f390c530f4a5a/pyproject.toml#L10)

I'll add a section right now to the readme about how to install the dependencies using poetry

**Comment by thebitanpaul** [comment]
Thank you for your humble guidance. ♡

**Comment by thebitanpaul** [comment]
Thank you for your humble guidance. ♡
